encoding: utf-8
port: 5678
host: 127.0.0.1

title: 游钓四方的博客
keywords: [游钓四方, 骑行, 钓鱼, 提琴or萨克斯]
description: '钓五湖四海，交八方朋友'

exclude: [webpack.config.js, package.json, Gemfile, Gemfile.lock, src, node_modules]
plugins: [jekyll-paginate, jemoji]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
emoji:
    src: 'https://api.fooleap.org'
paginate: 10
repository: fooleap/fooleap.github.io

nickname: fooleap
home: https://blog.fooleap.org
api: https://api.fooleap.org
IMG_PATH: https://lhasa-1253887673.cos.ap-shanghai.myqcloud.com/assets/article
tongji: 'fa7ec982118ebd236663169678264582'
analytics: 'UA-16717905-7'