version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "8888:8888"
    command: jekyll serve --host 0.0.0.0 --port 8888 --watch
    environment:
      - HTTP_PROXY=http://localhost:10808
      - HTTPS_PROXY=http://localhost:10808