- name: Upload to COS
  uses: actions/setup-python@v4
  with:
    python-version: 3.9

- name: Setup coscmd
  run: sudo pip install coscmd

- name: Configure coscmd
  env:
    SECRET_ID: ${{ secrets.AKIDeAh3IONAnKm4A4oPs9Wp2FMZYO7kBPhx }}
    SECRET_KEY: ${{ secrets.HLH7rQsFSSHuKWTL2VpzxjLl3DJEg0CF }}
    BUCKET: ${{ secrets.Bucket }}
    REGION: ${{ secrets.Region }}
  run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

- name: Upload to COS
  run: coscmd upload -rfs --delete public/ /
